ktor:
    application:
        modules:
            - br.com.challenge.backend.ApplicationKt.module
    deployment:
        port: "$PORT:8082"

    environment: "$ENV:dev"

    cache: "redis://localhost:6379"
    messaging: "localhost:9092"

    dev:
        db:
            url: "jdbc:postgresql://localhost:5432/notification"
            user: "postgres"
            password: "root"
            driver: "org.postgresql.Driver"
            schema: "public"
            maxPoolSize: 5
