services:
  db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=fee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2
    container_name: fee-redis
    ports:
      - "6379:6379"